export const FILE_LIST_REQUEST = 'FILE_LIST_REQUEST'
export const FILE_LIST_SUCCESS = 'FILE_LIST_SUCCESS'
export const FILE_LIST_FAIL = 'FILE_LIST_FAIL'



export const FILE_LIST_MY_REQUEST = 'FILE_LIST_MY_REQUEST'
export const FILE_LIST_MY_SUCCESS = 'FILE_LIST_MY_SUCCESS'
export const FILE_LIST_MY_FAIL = 'FILE_LIST_MY_FAIL'
export const FILE_LIST_MY_RESET = 'FILE_LIST_MY_RESET'