# Generated by Django 5.0.6 on 2024-06-03 06:48

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[base.models.validate_file_size])),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.file'),
        ),
    ]
