# Generated by Django 5.0.6 on 2024-06-03 06:53

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_file_alter_files_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.FileField(upload_to='', validators=[base.models.validate_file_size]),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
