# Generated by Django 5.0.6 on 2024-06-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_files_file_name_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.TextField(default=None),
        ),
    ]
