# Generated by Django 5.0.6 on 2024-06-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_files_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.TextField(default=None, null=True),
        ),
    ]
