# Generated by Django 5.0.6 on 2024-06-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_files_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='filename',
        ),
    ]
